### PR TITLE
[es] Update Sidebar

### PR DESCRIPTION
**Pull request by C47D**
Update most of the sidebar to start again the spanish translation.

OT: Where can i get the up to date translation? I would like to do update the spanish translation on every lvgl release.

### CODE REVIEW

**Comment by kisvegabor** [comment]
> I would like to do update the spanish translation on every lvgl release.

Awesome!

> Where can i get the up to date translation?

It's a shame but I didn't update the documentation when `v5.3` was released. I'm planning to review and update it when before `v6.0` is released. The release is planned to June so the review of the documentation should be in May.

So I suggest to wait a little until the the Engils version is updated.

Probably we can open an issue to discuss translation related things.

**Comment by C47D** [comment]
That's OK, I will base the documentation on the current English docs until then.
Can this PR be merged?

**Comment by kisvegabor** [comment]
> That's OK, I will base the documentation on the current English docs until then.

Ok

> Can this PR be merged?

Yes

**Comment by kisvegabor** [comment]
I rebuilt and uploaded the docs.

**Comment by C47D** [comment]
Thanks @kisvegabor, i will keep the pull request coming, slow but steady.

**Pull request merged**
