### PR TITLE
Update indev.md

### PR DESCRIPTION
**Pull request by LiveSparks**
No element gets clicked if the point array is declared as const. It needs to be static.

### CODE REVIEW

**Comment by embeddedt** [comment]
It would be better to put a note that it can't go out of scope. As long as it's in scope for the entire lifetime of the program, the keyword used doesn't matter.

Also, it can be `static const`, not just `static`.

**Comment by LiveSparks** [comment]
I might not be understanding this correctly but since this a input driver, won't it always go out of scope?
Or is it necessary only when the driver is register in a non-main function?

**Comment by embeddedt** [comment]
> I might not be understanding this correctly but since this a input driver, won't it always go out of scope?

Not if you made it a global variable.

My point is that there are many ways to do it, so I think adding a note about it is better than making people write their code a certain way.

**Comment by LiveSparks** [comment]
> My point is that there are many ways to do it, so I think adding a note about it is better than making people write their code a certain way.

What change would you suggest?

**Comment by embeddedt** [comment]
Add a note like "the array can't go out of scope while LittlevGL is running (i.e. use a global variable, or a`static` variable inside the function)."

**Comment by embeddedt** [comment]
Thank you!

@kisvegabor I'm still pretty busy; could you rebuild the `master` branch when you get a chance?

**Comment by kisvegabor** [comment]
Updated, thank you for both of you!

**Pull request merged**
