### PR TITLE
Update Display

### PR DESCRIPTION
**Pull request by ajithpv**
Modify the display section under overview for better clarity.

### CODE REVIEW

**Comment by embeddedt** [comment]
Thanks! I made some changes to make it easier to understand in certain parts.

**Comment by ajithpv** [comment]
@embeddedt , I have found one more typo in the color macro as below:

Selection_642

Should we change it to [standard](https://en.wikipedia.org/wiki/Maroon) name? Is this macro using in all the places?

**Comment by kisvegabor** [comment]
@ajithpv [LV_COLOR_MAROON](https://github.com/littlevgl/lvgl/blob/master/src/lv_misc/lv_color.h#L45) is used correctly in the code. `LV_COLOR_WHITE` is really missing.

**Comment by kisvegabor** [comment]
I've fixed them here: https://github.com/littlevgl/docs/commit/f16e237102e6685b41fa2d8ecdf14e64310734cc

**Pull request merged**
